baseURL = 'https://eitanadler.com/'
languageCode = 'en-us'
title = 'Eitan Adler'

theme = [ 'hugo-resume' ]

enableGitInfo = true

[params]
address = "San Francisco, CA"
email = "eitan@eitanadler.com"
favicon = "/favicon.ico"
firstName = "Eitan"
lastName = "Adler"
profileImage = "img/EitanAdlerHeadshotV1.jpg"
showQr = false
showContact = true
showBoards  = false
showCertifications = false
showSocializations = false
sections = ["education", "experience", "contributions"]
# sections = ["education", "contributions", "training"]
# sections = ["skills","publications","creations","contributions","experience","education","blog"]

[outputs]
  home = ["HTML", "JSON", "RSS"]
